trainer:
    name             : QTrainer
    nEpisodes        : 5
    episodeLength    : 1000
    batchSize        : 32
    prePopulateSteps : 64
    discountRate     : 0.8

env:
    name : SpaceInvadersDeterministic-v4

nets:
    net1:
        name : QNetwork

optimizers:
    optimizer1:
        name : Adam
        lr   : 0.01

losses:
    loss1:
        name : MSELoss

memory:
    name     : QMemory
    capacity : 100

pipeline:
    name         : QPipeline
    normValue    : 255
    traceLen     : 4
    offsetHeight : 8
    offsetWidth  : 4
    cropHeight   : 110
    cropWidth    : 84

agent:
    name             : QAgent
    epsilonStart     : 1.0
    epsilonStop      : 0.01
    epsilonDecayRate : 0.001

io:
    checkpointBase : spaceinvaders
    checkpointFreq : 1
    outputDir      : $HOME/data/ai_data
